export type IpcChannels =
  | "auth:start-login"
  | "auth:reauthorize"
  | "auth:logout"
  | "auth:get-status"
  | "proxy:start"
  | "proxy:stop"
  | "proxy:get-status"
  | "token:get-info"
  | "config:get"
  | "models:get-available"
  | "models:get-selected"
  | "models:set-selected"
  | "settings:get-auto-start"
  | "settings:set-auto-start"
  | "codespace:check-gh-cli"
  | "codespace:list"
  | "codespace:list-active-vscode"
  | "codespace:connect"
  | "codespace:disconnect"
  | "codespace:disconnect-all"
  | "codespace:dismiss"
  | "codespace:get-connections";

export type IpcEvents =
  | "auth:status-changed"
  | "proxy:status-changed"
  | "token:info-changed"
  | "proxy:request-log"
  | "codespace:status-changed"
  | "codespace:connection-error";
