export type IpcChannels =
  | "auth:start-login"
  | "auth:logout"
  | "auth:get-status"
  | "proxy:start"
  | "proxy:stop"
  | "proxy:get-status"
  | "token:get-info"
  | "config:get"
  | "models:get-available"
  | "models:get-selected"
  | "models:set-selected"
  | "settings:get-auto-start"
  | "settings:set-auto-start"
  | "codespace:check-gh-cli"
  | "codespace:list"
  | "codespace:connect"
  | "codespace:disconnect"
  | "codespace:disconnect-all"
  | "codespace:get-connections"
  | "codespace:start-auto-detect"
  | "codespace:stop-auto-detect"
  | "codespace:get-auto-detect-state"
  | "codespace:set-auto-connect-config"
  | "codespace:retry-scope-connections";

export type IpcEvents =
  | "auth:status-changed"
  | "proxy:status-changed"
  | "token:info-changed"
  | "proxy:request-log"
  | "codespace:status-changed"
  | "codespace:connection-error"
  | "codespace:auto-detected"
  | "codespace:auto-connected"
  | "codespace:auto-disconnected"
  | "codespace:scope-required"
  | "codespace:auto-connect-error";
